### ISSUE TITLE
HandShake Exception

### ISSUE THREAD

**Issue by kamrancr7** [vukoye/xmpp_dart#9]
while running the app it shows me the following error in log:

```
I/flutter (20230): DONE PARSING FATURES
I/flutter (20230): State: XmppConnectionState.DoneParsingFeatures
E/flutter (20230): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (20230): 	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:354))
E/flutter (20230): #0      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:103:51)
E/flutter (20230): #1      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:832:21)
E/flutter (20230): #2      _RawSecureSocket._tryFilter.<anonymous closure> (dart:io/secure_socket.dart:953:13)
E/flutter (20230): #3      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (20230): #4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (20230): #5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter (20230): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter (20230): #7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter (20230): #8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter (20230): #9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter (20230): #10     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (20230): #11     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (20230): #12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (20230): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (20230): #14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (20230): #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter (20230): 
```

**Comment by vukoye** [comment]
This looks like dart certificate issue:
https://github.com/flutter/flutter/issues/23045

**Comment by vukoye** [comment]
Please retest with latest version.
